# Generated by Django 5.1.1 on 2024-09-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_joined_date_member_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
